discourse/discourse-assign

config/locales/client.fi.yml, config/locales/server.fi.yml
Includes the client and server files of config.
=> Create Finnish locale

app/controllers/discourse_assign/assign_controller.rb, spec/requests/assign_controller_spec.rb
Also, how to run the unit tests for this engine?
I tried by cloning this code in discourse and running specs there. Is there a better way to do it?
Shouldn't tests be run on PR in this repo too?
=> do not assign to same user again

app/models/remind_assigns_frequency_site_settings.rb, config/locales/client.en.yml, config/locales/server.en.yml, config/settings.yml, db/migrate/20190422200243_add_last_reminded_at_index.rb, db/migrate/20190422200243_add_last_reminded_to_user.rb, jobs/regular/remind_user.rb, jobs/scheduled/enqueue_reminders.rb, lib/pending_assigns_reminder.rb, plugin.rb, spec/jobs/scheduled/enqueue_reminders_spec.rb, spec/lib/pending_assigns_reminder_spec.rb
- New `SiteSetting` to set reminders frequency.
- Sends a PM as a reminder of assigned tasks:
- Only if `tasks >= 1`.
=> FEATURE: Remind users of assigned tasks.

assets/javascripts/discourse/templates/mobile/components/assigned-topic-list-item.hbs, assets/javascripts/discourse/templates/mobile/components/basic-assigned-topic-list.hbs, assets/stylesheets/assigns.scss
=> FIX: Add a custom mobile view for the assigned-topics-list

config/settings.yml, jobs/scheduled/enqueue_reminders.rb, lib/topic_assigner.rb, plugin.rb, spec/models/group_spec.rb, spec/requests/assign_controller_spec.rb
Reverts discourse/discourse-assign#38
=> Revert "DEV: use group ids to allow assign on groups"

config/settings.yml, db/migrate/20190718144722_set_assign_allowed_on_groups_default.rb, jobs/scheduled/enqueue_reminders.rb, lib/topic_assigner.rb, plugin.rb, spec/models/group_spec.rb, spec/requests/assign_controller_spec.rb
This PR reverts the revert of #38.
=>  DEV: use group ids to allow assign on groups [Undo Revert] 

assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6, assets/javascripts/discourse/widgets/quick-access-assignments.js.es6
> CONTEXT: [Quick access to bookmarks and messages on user menu](https://meta.discourse.org/t/quick-access-to-bookmarks-and-messages-on-user-menu/32787/12?u=xrav3nz)
> Related Core PR: https://github.com/discourse/discourse/pull/8073
Open to suggestions, thanks!
=> FEATURE: Quick access panel for assignments.

app/controllers/discourse_assign/assign_controller.rb, app/serializers/assigned_topic_serializer.rb, app/serializers/assigned_user_serializer.rb, config/routes.rb, plugin.rb
This makes it easier to retrieve assigned list through API.
=> FIX: System user should be allowed to use plugin.

assets/javascripts/discourse/components/assigned-topic-list-item.js.es6
This PR in discourse core:
https://github.com/discourse/discourse/pull/8589
makes a breaking change in this plugin. This is a fix for it.
=> FIX: Update topic-list-item to reflect changes in core

assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6, plugin.rb
Add assigned to user to bookmark serializers, and also add to JS bookmark model for the route to assigned user.
**DO NOT MERGE until https://github.com/discourse/discourse/pull/8999/files is merged**
=> DO NOT MERGE - FEATURE: Add assigned to user to bookmark serializers

plugin.rb
Related: https://github.com/discourse/discourse/pull/9236
=> FIX: Preload assigned users for BookmarkQuery

assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
Fairly simple feature add here. Commit message says it all!
=> FEATURE: Add 'g a' as keyboard shortcut to assigned list

assets/javascripts/discourse/components/assign-actions-dropdown.js.es6
assigned-topic-list dropdown translation issue solved
=> assigned-topic-list dropdown translation issue solved

app/controllers/discourse_assign/assign_controller.rb, plugin.rb
See https://github.com/discourse/discourse/pull/10253
=> DEV: Change to use UserLookup for core change

assets/javascripts/discourse-assign/connectors/group-reports-nav-item/assigned-topic-list.hbs, assets/javascripts/discourse-assign/connectors/group-reports-nav-item/assigned-topic-list.js.es6, assets/javascripts/discourse/components/group-assignments-filter.js.es6, assets/javascripts/discourse/components/group-assignments-menu-item.js.es6, assets/javascripts/discourse/templates/components/group-assignments-filter.hbs, assets/javascripts/discourse/templates/components/group-assignments-menu-item.hbs, assets/javascripts/discourse/templates/group/assignments.hbs, assets/stylesheets/assigns.scss, assets/stylesheets/mobile/assigns.scss
=>  UX: Improving styling so names/usernames fit better 

assets/javascripts/discourse/widgets/quick-access-assignments.js.es6
See https://github.com/discourse/discourse/commit/1972364d0f1b7907e726a8fce5a21a2d57f84b18
=> Update for refactored quick access panels

plugin.rb
Related PR on core: https://github.com/discourse/discourse/pull/11428
=> FEATURE: show assigned user on search results

test/javascripts/acceptance/quick-access-assignments-test.js.es6
Related to https://github.com/discourse/discourse/pull/11789
=> DEV: Update test to pass if the assignments tab is either a link or a button.

assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
Fixes a regression introduced in #173.
=> FIX: TagsHtmlCallback params can be undefined

assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
Depends on https://github.com/discourse/discourse/pull/13813
=> UX: Add quick search suggestion entries

plugin.rb, spec/components/topic_query_spec.rb
Meta ref: https://meta.discourse.org/t/filter-by-nobody-seems-broken/197770/
=> FIX: filter by "nobody" was broken

test/javascripts/acceptance/assign-disabled-test.js.es6, test/javascripts/acceptance/assign-enabled-test.js.es6, test/javascripts/acceptance/assigned-topic-test.js.es6, test/javascripts/acceptance/group-assignments-test.js.es6, test/javascripts/acceptance/quick-access-assignments-test.js.es6, test/javascripts/acceptance/search-full-test.js.es6, test/javascripts/acceptance/un-assign-from-list-test.js.es6, test/javascripts/components/group-assigned-filter-test.js.es6
Included:
* DEV: Add "assigned topic" test
* DEV: Update and re-enable disabled test
* DEV: Add missing imports
* DEV: Fix typos
* DEV: Don't use find()
* DEV: Use the hbs helper
=> DEV: Update tests

assets/javascripts/discourse-assign/controllers/assign-user.js.es6, assets/javascripts/discourse/templates/modal/assign-user.hbs
Also drops autofocus as it's the first item in the form
=> FIX: explicit assign on user selection

config/locales/client.en.yml, config/locales/server.en.yml, lib/random_assign_utils.rb, plugin.rb
- Makes a best attempt at being random and assigning people who haven’t been assigned for a long time
- Uses timezones and holidays
- Allows to define a minimum delay between assignments
- Creates a post if no one is available
=> FEATURE: improves random assign automation

spec/components/topic_query_spec.rb
We were creating PM topics that did not have any posts.
=> FIX: Properly fabricate data for topic query specs.

assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
The first post showed the assign status when it was loaded and did not
update if it changed. The page had to be refreshed for the text to be
updated.
=> FIX: Refresh first post after assign and unassign

assets/javascripts/discourse/templates/components/assigned-topic-list.hbs, assets/javascripts/discourse/templates/components/basic-assigned-topic-list.hbs, assets/javascripts/discourse/templates/group-topics-list.hbs
Fixes following core change in: https://github.com/discourse/discourse/pull/14419
=> DEV: Update bulk select in group topics list

app/controllers/discourse_assign/assign_controller.rb, app/models/assignment.rb, assets/javascripts/discourse-assign/controllers/assign-user.js.es6, assets/javascripts/discourse-assign/controllers/group-assigned-show.js.es6, assets/javascripts/discourse-assign/controllers/user-activity-assigned.js.es6, assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6, assets/javascripts/discourse/components/assign-actions-dropdown.js.es6, assets/javascripts/discourse/services/task-actions.js.es6, assets/javascripts/discourse/templates/components/assigned-topic-list-item.hbs, assets/javascripts/discourse/templates/mobile/components/assigned-topic-list-item.hbs, assets/javascripts/discourse/templates/modal/assign-user.hbs, assets/stylesheets/assigns.scss, config/locales/client.en.yml, config/locales/server.en.yml, db/migrate/20211014043735_remove_topic_id_index.rb, jobs/regular/assign_notification.rb, jobs/regular/unassign_notification.rb, lib/assigner.rb, lib/discourse_assign/helpers.rb, plugin.rb, spec/jobs/regular/assign_notification_spec.rb, spec/jobs/regular/unassign_notification_spec.rb, spec/serializers/flagged_topic_serializer_spec.rb, test/javascripts/acceptance/assign-enabled-test.js.es6, test/javascripts/acceptance/assigned-topic-test.js.es6
Ability to assign an individual post to a user or group
https://user-images.githubusercontent.com/72780/138999800-b0b81242-981d-4098-afce-4d7b02ab7e71.mov
=> FEATURE: assign to post

plugin.rb
Missing icon and missing indirect assignments in search
=> Missing icon in search

config/locales/client.en.yml, lib/assigner.rb
When a post is assigned/unassigned, we want small action to have a link to the specific post.
Related PR: https://github.com/discourse/discourse/pull/14816
=> FEATURE: small post action with link to post

assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6, lib/assigner.rb
Update topic title, first post and related post
https://user-images.githubusercontent.com/72780/140664975-d30b96b7-3119-45b3-8aa6-2ddde466f515.mov
=> FIX: correctly update UI when post is assigned/unassigned

assets/javascripts/discourse-assign/routes/group-assigned-show.js.es6
See https://github.com/discourse/eslint-config-discourse/commit/4f7aba06c03fdd22bb26669aeb8ed4af3127c409
=> DEV: Update code for eslint object-shorthand-rule

app/controllers/discourse_assign/assign_controller.rb, assets/javascripts/discourse-assign/controllers/assign-user.js.es6, assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6, assets/javascripts/discourse/services/task-actions.js.es6, assets/javascripts/discourse/templates/modal/assign-user.hbs, assets/stylesheets/assigns.scss, assets/stylesheets/mobile/assigns.scss, config/locales/client.en.yml, config/routes.rb, lib/assigner.rb, test/javascripts/acceptance/assigned-topic-test.js.es6
Build a new workflow that adds a dropdown in place of the old `assign` button with the ability to 
- Re-assign a new user / group to an assigned topic
- Re-assign yourself to an assigned topic
- Unassign a user / group from an assigned topic
=> FEATURE: Reassign workflow

assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
- Add proper aria label to dropdown
- Make sure footer button aria-labels are returned
fixes : https://dev.discourse.org/t/quicker-assign-to-self-when-group-is-assigned/54647/24?u=isaacjanzen
=> FIX: Return proper aria-labels

assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6, assets/stylesheets/assigns.scss
- Make drop down options regular font weight
- Add icon to drop down options
=> UX: Update reassign dropdown styles

assets/javascripts/discourse-assign/connectors/advanced-search-options-below/assigned-advanced-search.hbs, assets/javascripts/discourse/templates/modal/assign-user.hbs
Change after https://github.com/discourse/discourse/pull/14933
=> FIX: use customOptions property

assets/javascripts/discourse-assign/controllers/group-assigned-show.js.es6, assets/javascripts/discourse-assign/controllers/user-activity-assigned.js.es6, assets/javascripts/discourse/templates/group-topics-list.hbs, assets/javascripts/discourse/templates/group/assigned.hbs, assets/javascripts/discourse/templates/user-assigned-topics.hbs
=> FIX: Broken assigned topics search

assets/javascripts/discourse-assign/connectors/advanced-search-options-below/assigned-advanced-search.js.es6, assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
=> FIX: Selecting a user was clearing search terms

spec/jobs/regular/assign_notification_spec.rb
Broken by https://github.com/discourse/discourse/commit/9f8ee8f1372eab643951a49440024ee0fdbdf792
=> DEV: Fix spec

assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
1. When post is assigned to current user, unassign icon is not hidden
2. Link under names lead to topic (when topic assignment) and to post (when post assignment)
=> FIX: improvements for assign to post

app/controllers/discourse_assign/assign_controller.rb, assets/javascripts/discourse-assign/controllers/assign-user.js.es6, assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6, assets/javascripts/discourse/services/task-actions.js.es6, assets/javascripts/discourse/templates/modal/assign-user.hbs, config/routes.rb, lib/assigner.rb, lib/random_assign_utils.rb
Fixes: https://dev.discourse.org/t/self-assign-is-not-working-on-mobile/56331/21?u=isaacjanzen
- Combines assign and reassign logic... removing bulky and extra logic
=> FIX: Refactor assign / reassign to combine logic

plugin.rb
Search similarly to topic list should return a hash with post_number
=> FIX: indirect assigned to in search

spec/components/search_spec.rb
Yesterday a quick fix was made with this PR https://github.com/discourse/discourse-assign/pull/266
Here are additional specs to ensure that seralizer not throwing an error anymore
=> FIX: specs for search fix

plugin.rb
Additional check was added to only refresh if there were affected assignments
=> FIX: refresh topic when topic or post is deleted or recovered

lib/assigner.rb
https://meta.discourse.org/t/discourse-assign/58044/164?u=rgj
=> Fix: set these fields in condition below only

config/locales/client.en.yml
Routing was fixed in https://github.com/discourse/discourse/pull/15536
=> FIX: Use Ember router for small action post links

spec/lib/assigner_spec.rb, spec/serializers/topic_view_serializer_spec.rb
For topic view serializer and message bus
=> DEV: Backfill tests

app/controllers/discourse_assign/assign_controller.rb, app/models/assignment.rb, assets/javascripts/discourse-assign/controllers/assign-user.js, assets/javascripts/discourse-assign/initializers/extend-for-assigns.js, assets/javascripts/discourse/services/task-actions.js, assets/javascripts/discourse/templates/modal/assign-user.hbs, assets/stylesheets/assigns.scss, config/locales/client.en.yml, db/migrate/20220429110203_add_note_to_assignments.rb, lib/assigner.rb, plugin.rb, spec/lib/assigner_spec.rb, spec/requests/assign_controller_spec.rb, spec/serializers/post_serializer_spec.rb, spec/serializers/topic_view_serializer_spec.rb
Add assign note to assignment /64635
Subsequent PR https://github.com/discourse/discourse-assign/pull/327 based on this branch shows assignment note in tooltip.
https://user-images.githubusercontent.com/1555215/166009891-746120ea-5dd3-46f1-b642-ab0b54006249.mov
=> FEATURE: Add assign note

assets/javascripts/discourse-assign/initializers/extend-for-assigns.js, lib/assigner.rb, lib/discourse_assign/helpers.rb, plugin.rb, spec/components/search_spec.rb, spec/lib/assigner_spec.rb, spec/serializers/topic_view_serializer_spec.rb, test/javascripts/acceptance/assigned-topic-test.js
To be merged after https://github.com/discourse/discourse-assign/pull/326. Related /64635
https://user-images.githubusercontent.com/1555215/166009725-0b73ce05-207d-4b55-ba31-ad7eb87bcd10.mov
=> FEATURE: Show note in tooltip

jobs/regular/assign_notification.rb, lib/assigner.rb, plugin.rb, spec/jobs/regular/assign_notification_spec.rb, spec/jobs/regular/unassign_notification_spec.rb, spec/lib/assigner_spec.rb
Mainly better variable names while implementing updates for notes. Since this is a refactor that's covered by tests, no additional tests are added.
=> DEV: Small refactors for future work

assets/javascripts/discourse-assign/controllers/assign-user.js, test/javascripts/controllers/assign-user-test.js
=> FIX: Only assign when suggestion is clicked

plugin.rb
The previous query which uses a subquery in combination with the OR
condition results in the PG planner unable to leverage the indexes we
have available. Instead, the PG planner would loop through each user
record and execute the subquery once per row. As the number of users on
a site increases, this query becomes more and more expensive to run
leading to the query timing out once a certain threshold is reached.
In the new query, we remove the OR condition which allows the PG
planner to the existing indexes more effectively. We also improved the
subquery by removing an unnecessary join against the groups table.
Since `group_users` rows are cleaned up when a group is destroyed so there is
no need for the inner join on the `groups` table.
=> PERF: Speed up `User.assign_allowed` SQL query

assets/javascripts/discourse/services/task-actions.js, test/javascripts/unit/task-actions-test.js
https://user-images.githubusercontent.com/1555215/174345166-b92c3f4a-13c7-4fd0-a3b7-7f0b05af2cef.mov
=> FIX: Don't reuse assign note when reassigning

assets/javascripts/discourse/components/user-menu/assigns-list.js, test/javascripts/acceptance/assigns-tab-user-menu-test.js
See https://github.com/discourse/discourse/pull/18081 and https://github.com/discourse/discourse/pull/18087.
=> DEV: Apply model transformations for the assigns list in the experimental user menu

assets/javascripts/discourse/components/user-menu/assigns-list.js, test/javascripts/acceptance/assigns-tab-user-menu-test.js
Use `grouped_unread_notifications` instead of `grouped_unread_high_priority_notifications`
Related PR: https://github.com/discourse/discourse/pull/18132
=> FIX: use grouped_unread_notifications

assets/javascripts/discourse/components/user-menu/assigns-list.js, assets/javascripts/discourse/initializers/assign-user-menu.js
Related PR: https://github.com/discourse/discourse/pull/18164
=> FIX: defined notifications types for user menu

spec/lib/assigner_spec.rb, spec/requests/assign_controller_spec.rb, spec/serializers/topic_list_serializer_spec.rb
This hack is no longer necessary.
=> DEV: Admins and mods are already members of staff

assets/javascripts/discourse-assign/controllers/assign-user.js, assets/javascripts/discourse-assign/initializers/extend-for-assigns.js, assets/javascripts/discourse/services/task-actions.js, assets/javascripts/discourse/templates/modal/assign-user.hbs, assets/stylesheets/assigns.scss, config/locales/client.en.yml, test/javascripts/acceptance/assign-enabled-test.js, test/javascripts/unit/task-actions-test.js
Needs https://github.com/discourse/discourse/pull/19521.
Before:
After:
=> UX: Improve assign modal design

.github/workflows/plugin-linting.yml, .github/workflows/plugin-tests.yml, .rubocop.yml, .streerc, Gemfile.lock, lib/discourse_calendar.rb, lib/random_assign_utils.rb, spec/lib/assigner_spec.rb, spec/requests/assign_controller_spec.rb
Adds syntax_tree configuration and formats code
=> DEV: Introduce syntax_tree for ruby formatting

app/controllers/discourse_assign/assign_controller.rb
The suggestions are displayed in email-group-user-chooser and user status is displayed if it exists.
=> FEATURE: Show user status when searching assignees

assets/javascripts/discourse-assign/controllers/assign-user.js, assets/javascripts/discourse/templates/modal/assign-user.hbs
Automatically expand the assignee user chooser when showing the assign modal.
=> FEATURE: Automatically open assignee chooser

assets/javascripts/discourse-assign/controllers/assign-user.js, assets/javascripts/discourse/components/assignee-chooser-row.js, assets/javascripts/discourse/components/assignee-chooser.js, assets/javascripts/discourse/templates/components/assignee-chooser-row.hbs, assets/javascripts/discourse/templates/modal/assign-user.hbs, assets/stylesheets/assigns.scss, config/locales/client.en.yml
=> UX: Add suggestions label to assign modal

plugin.rb
Followup to 1dd0be91340e88558b65532d1347f5af0f2fd9e2
=> DEV: Remove unneeded argument for add_to_serializer

assets/javascripts/discourse-assign/connectors/group-reports-nav-item/assigned-topic-list.hbs, assets/javascripts/discourse-assign/connectors/user-preferences-notifications/remind-assigns-frequency.hbs, assets/javascripts/discourse/templates/components/assigned-topic-list-item.hbs, assets/javascripts/discourse/templates/components/assigned-topic-list.hbs, assets/javascripts/discourse/templates/components/basic-assigned-topic-list.hbs, assets/javascripts/discourse/templates/group-topics-list.hbs, assets/javascripts/discourse/templates/group/assigned.hbs, assets/javascripts/discourse/templates/mobile/components/assigned-topic-list-item.hbs, assets/javascripts/discourse/templates/mobile/components/basic-assigned-topic-list.hbs, assets/javascripts/discourse/templates/modal/assign-user.hbs, assets/javascripts/discourse/templates/user-activity-assigned.hbs, package.json, yarn.lock
=> DEV: Use angle bracket syntax

spec/system/assign_topic_spec.rb
For some reason sometimes clicking the admin wrench doesn't work
=> DEV: Try fix flaky spec

spec/requests/assign_controller_spec.rb
Hopefully makes things less flakey by
- Not fabricating in `before`
Also
- Use fabricators instead of the `Assigner` to set up tests
- Be specific about users and groups
=> DEV: Fabricate assignments

assets/javascripts/discourse/components/user-menu/assigns-list.js, test/javascripts/acceptance/assigns-tab-user-menu-test.js
Relies upon: https://github.com/discourse/discourse/pull/22262
Context can be found ☝️ as well.
=> DEV: Convert dismiss modal to component-based API

assets/stylesheets/assigns.scss
=> FIX: missing space in assign button

lib/pending_assigns_reminder.rb
=> DEV: Fix a core deprecation

spec/system/assign_topic_spec.rb
cc: @jancernik @martin-brennan @tgxworld (see: https://github.com/discourse/discourse/actions/runs/6145275929/job/16672332926)
=> DEV: Skip a flaky spec

app/models/assignment.rb, plugin.rb, spec/models/assignment_spec.rb, spec/plugin_spec.rb
Currently, when reopening a topic that has assignments, the notifications in the user menu aren’t recreated.
This PR fixes that issue. It also addresses the same type of issue with posts being destroyed and recovered.
=> FIX: Recreate notifications on topic reopening

test/javascripts/acceptance/assigns-tab-user-menu-test.js
In preparation for https://github.com/discourse/discourse/pull/26467
=> DEV: Update test selectors for glimmer header

assets/javascripts/discourse/components/assign-button.gjs, assets/javascripts/discourse/initializers/extend-for-assigns.js, test/javascripts/acceptance/assign-enabled-test.js, test/javascripts/acceptance/assign-enabled-widget-post-menu-test.js
Requires https://github.com/discourse/discourse/pull/28670
=> DEV: Added compatibility with the Glimmer Post Menu
