discourse/discourse-assign

- config/locales/client.de.yml
- config/locales/server.de.yml
I translated the "assign" with "zuordnen" rather than "zuweisen", which sounds a little too much like a commanding tone. Sadly, in any variant there will be two words for the translation of "unassign" ("Zuordnung aufheben"). This lets the assign button become equally wide as the bookmark button. However, it seems to fit and is not too ugly (see screenshot)
The rest of the texts are as short as possible… Sometimes it's hard to write short sentences in German 😄
> Add german locale

- app/controllers/discourse_assign/assign_controller.rb
- config/locales/server.en.yml
- config/settings.yml
- lib/topic_assigner.rb
- spec/lib/topic_assigner_spec.rb
- spec/requests/assign_controller_spec.rb
- Move domain validations inside the `TopicAssigner` to avoid duplicating them.
- Expose a `max_assigned_topics` setting.
- Do not assign a topic to a user if it'll exceed this limit.
- Do not suggest users who have already reached the limit.
> FEATURE: Limit the amount of assigned topics an user can have.

- plugin.rb
- spec/integration/assign_spec.rb
This PR bypasses the callbacks defined for `assign_locks_flags` and `flags_require_assign` since the queue was deprecated in favor of the new Reviewable API.
There's no need to change client code since the connectors will never be used (the queue was removed). However, we'll leave them there for backward compatibility reasons.
> Disable flagging behaviour in favor of the new reviewable API

- jobs/scheduled/enqueue_reminders.rb
- spec/jobs/scheduled/enqueue_reminders_spec.rb
With an empty SiteSetting.assign_allowed_on_groups, it used to generate
an invalid query containing "group_users.group_id IN ()".
> FIX: Skip enqueuing reminders if no groups are allowed.

- config/settings.yml
- jobs/scheduled/enqueue_reminders.rb
- lib/topic_assigner.rb
- plugin.rb
- spec/models/group_spec.rb
- spec/requests/assign_controller_spec.rb
The build is broken because this depends on https://github.com/discourse/discourse/pull/7860
This PR let us use group IDs as default values for the `assign_allowed_on_groups` setting.
To maintain backwards compatibility, we also ship:
- A way to migrate the setting values only after being sure the core's code is available.
- A way to keep the feature working when we still have group names instead of IDs
> DEV: use group ids to allow assign on groups

- app/controllers/discourse_assign/assign_controller.rb
- config/locales/server.en.yml
- lib/topic_assigner.rb
- spec/components/topic_query_spec.rb
- spec/integration/assign_spec.rb
- spec/lib/pending_assigns_reminder_spec.rb
- spec/lib/topic_assigner_spec.rb
- spec/requests/assign_controller_spec.rb
- spec/serializers/topic_list_serializer_spec.rb
- spec/support/assign_allowed_group.rb
As discussed [here](https://meta.discourse.org/t/bug-possible-for-admin-to-assign-pm-to-moderator-who-does-not-have-access-to-the-pm/116571/6), it shouldn't be possible to assign a topic to a user when:
- The user won't be able to see the topic.
- The user is not a member of the assign allowed users.
This PR adds some backend rules to prevent these scenarios.
> FEATURE: New rules for assigning a topic.

- app/controllers/discourse_assign/assign_controller.rb
Otherwise, the user would search in groups that were not visible,
operation which resulted in a 403 error.
> FIX: Suggest only groups that are visible to current user

- assets/javascripts/discourse/widgets/quick-access-assignments.js.es6
> CONTEXT: https://meta.discourse.org/t/quick-access-to-bookmarks-and-messages-on-user-menu/32787/50
This relies on the `escapedContent` attribute introduced in https://github.com/discourse/discourse/pull/8095.
Thanks!
> FIX: do not escape `fancy_title` again.

- test/javascripts/acceptance/quick-access-assignments-test.js.es6
This is a test-only change for the "quick access assignments" feature introduced in https://github.com/discourse/discourse-assign/pull/49.
Thanks!
> TEST: Acceptance test for quick access assignments

- jobs/regular/remind_user.rb
- jobs/scheduled/enqueue_reminders.rb
Zeitwerk is failing when we are searching for Jobs::Onceoff and Jobs::Base without going back to the top-level namespace (this is correlated to the fact that we got Onceoff base class and module with the same name). 
I noticed that in plugins we are using sometimes :: and sometimes not and that gives me comfort that this change will not break anything.
Travis error: https://travis-ci.org/discourse/discourse/jobs/585072364
> [WIP] FIX: Use top-level namespace for base classes

- config/settings.yml
The old default path is not showing up all assigned topics if user has
muted categories or tags.
> UX: Update default path to users assigned topics

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
This is a bit more robust, site settings are not always injected (for example in raw handlebars templates).
> DEV: use site settings from container

- assets/stylesheets/assigns.scss
"we can't use flex for buttons yet" – now we can, and we do! https://github.com/discourse/discourse/commit/e71f5e8951bcffdaac3476d96efaa2232b809a4c
Fixes an issue with assign button height in some themes.
Before/after:
Core theme, no change:
> FIX: Don't set assign button's height

- assets/javascripts/discourse-assign/controllers/group-assigned-show.js.es6
- assets/javascripts/discourse-assign/controllers/group-assigned.js.es6
- assets/javascripts/discourse-assign/controllers/user-activity-assigned.js.es6
- assets/javascripts/discourse-assign/routes/group-assigned-show.js.es6
- assets/javascripts/discourse-assign/routes/user-activity-assigned.js.es6
- assets/javascripts/discourse/templates/components/group-assigned-filter.hbs
- assets/javascripts/discourse/templates/group/assigned.hbs
- plugin.rb
- spec/requests/list_controller_spec.rb
This significantly reduces the amount of logic we need to carry in the discourse-assign plugin. One side effect is that I had to rename the 'q' parameter to 'search', so that it matches core's implementation.
Requires https://github.com/discourse/discourse/pull/10647 to be merged first
> REFACTOR: Use core `default_results` function

- assets/javascripts/discourse/components/remind-assigns-frequency.js.es6
- assets/javascripts/discourse/templates/components/remind-assigns-frequency.hbs
Before this commit, changing the value of the reminder frequency on a user notifications page was not working.
This commit also get rid of a few deprecations warning.
> FIX: removes the need for intermediate property and updates code

- assets/javascripts/discourse/templates/components/remind-assigns-frequency.hbs
Before this fix it was impossible for a user to change their preference
for reminder frequency.
> FIX: `onChange` needs an action

- assets/stylesheets/assigns.scss
This PR adds some margins to the assign tags in the composer-popup.
Before 
After
> UX: adds margins to the assign tag in composer-popup

- assets/javascripts/discourse-assign/controllers/group-assigned-show.js.es6
- assets/javascripts/discourse-assign/controllers/group-assigned.js.es6
- assets/javascripts/discourse-assign/controllers/user-activity-assigned.js.es6
- assets/javascripts/lib/debounce.js.es6
We recently merged a Discourse core's PR to replace usages of Ember's debounce and discourseDebounce with a new debounce wrapper. The new wrapper works exactly like Ember's debounce but internally calls "run" when called in test mode.
This PR replaces all usages of other debounce functions with the new wrapper and fallbacks to Ember's debounce for backward-compatibility.
> DEV: Use the new discourseDebounce function wrapper.

- plugin.rb
- spec/plugin_spec.rb
Users that aren't members of an assign allowed group can no longer use the feature. Automatically unassign all their topics.
> FIX: Unassign users after removing them from an assign allowed group.

- app/controllers/discourse_assign/assign_controller.rb
- config/locales/server.en.yml
- lib/topic_assigner.rb
- spec/lib/topic_assigner_spec.rb
- spec/requests/assign_controller_spec.rb
Currently if you try to assign a PM to a user who can't see it, you get an error message that says "@{user} can't be assigned since they don't belong to assigned allowed groups". This commit improves the message and now it tells you the user doesn't have access to the PM and that you need to invite the user before you can assign them.
> UX: Improve error message when assigning a PM to a user who doesn't have access to the PM

- assets/stylesheets/assigns.scss
Follow up to f7bb92b
I could have completely removed the vertical padding like it was previously, but reducing it works similarly and also prevents the button from collapsing completely if it wraps to its own line.
> Adjust button padding to account for avatar

- assets/javascripts/lib/debounce.js.es6
We need to wrap the new debounce function inside a try block to avoid throwing a "module not found" exception.
>  FIX: Use Ember's debounce on stable.

- assets/javascripts/discourse-assign/controllers/assign-user.js.es6
- assets/javascripts/discourse/templates/modal/assign-user.hbs
The users chooser on the assign modal is the primary input field on the modal, so it makes to shift focus to it when the modal is opened. This PR needs https://github.com/discourse/discourse/commit/0f807ba85b869fffc9560d97632d3ca7471e7fc4 in core to work properly, but it won't cause errors (won't have any effects) if it's deployed to a site that doesn't have that commit.
> FIX: Add autofocus to users chooser on the assign modal

- assets/javascripts/discourse-assign/controllers/assign-user.js.es6
- test/javascripts/acceptance/assign-enabled-test.js.es6
Since this commit
https://github.com/discourse/discourse-assign/commit/195dcc92cb3bab9dd7b7457efb7beca06959baae
the updateUsername function was missing an @action decorator. This adds
it back and extends the assign acceptance tests to click the
mobile/desktop assign buttons and open the modal and click the
suggestion to save the assignment.
> FIX: Assign topic button not working

- db/post_migrate/20210709101534_move_assignments_from_custom_fields_to_a_table.rb
- db/post_migrate/20210714173022_correctly_move_assignments_from_custom_fields_to_a_table.rb
The order of values in the `INSERT` query was invalid (`assigned_to_id` and `topic_id` were swapped)
> FIX: CF to table migration was incorrect

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
Makes the assigned icon and label non-interactive in search results dropdown.
> FIX: Make tagsHtml callback respect tagName option

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
I think it should have been deleted with https://github.com/discourse/discourse-assign/pull/47? That's where e.g. `assign_locks_flags` site setting was removed.
> DEV: Remove old review queue code

- test/javascripts/acceptance/assign-enabled-test.js.es6
- test/javascripts/acceptance/assigned-topic-test.js.es6
- test/javascripts/acceptance/group-assignments-test.js.es6
- test/javascripts/acceptance/quick-access-assignments-test.js.es6
- test/javascripts/acceptance/search-full-test.js.es6
- test/javascripts/acceptance/un-assign-from-list-test.js.es6
- test/javascripts/components/group-assigned-filter-test.js.es6
I had discourse-assign installed on my local Discourse instance and one spec that has the same name as another spec in Core was causing the error when running qunit tests locally, the whole suite didn't want to run:
I've added a prefix to that spec (https://github.com/discourse/discourse-assign/commit/3aeeea3c8af13e5ee9c0fee6f5ae7b2c5c371241) and to the rest of them to avoid conflicts and make it easier to filter specs for the plugin during local development.
> DEV: add a prefix with the plugin name to spec names

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
- config/settings.yml
- test/javascripts/acceptance/category-test.js.es6
There's no need to display the "Unassigned" button for regular users when `assigns_public` is `false`.
> FIX: Hide Unassigned if user doesn't have access

- app/controllers/discourse_assign/assign_controller.rb
- assets/javascripts/discourse-assign/connectors/groups-interaction-custom-options/assignable-interaction-fields.hbs
- assets/javascripts/discourse-assign/connectors/groups-interaction-custom-options/assignable-interaction-fields.js.es6
- assets/javascripts/discourse-assign/controllers/assign-user.js.es6
- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
- assets/javascripts/discourse/templates/modal/assign-user.hbs
- config/locales/client.en.yml
- db/migrate/20210830024453_add_assignable_level_to_groups.rb
- lib/topic_assigner.rb
- plugin.rb
- spec/serializers/group_show_serializer_spec.rb
- spec/support/assign_allowed_group.rb
V1 of group assign was using "who can message" to determine if group can be assigned.
This PR is introducing new separate setting "who can assign"
Correlated PR https://github.com/discourse/discourse/pull/14216 (Specs will fail until core pr is merged)
> FEATURE: new assignable group option instead of messageable

- assets/javascripts/discourse-assign/connectors/advanced-search-options-below/assigned-advanced-search.hbs
Allow advance search filter to select topics assigned to specific group
> FEATURE: advance search groups

- app/controllers/discourse_assign/assign_controller.rb
- assets/javascripts/discourse-assign/controllers/group-assigned-show.js.es6
- assets/javascripts/discourse-assign/routes/group-assigned-show.js.es6
- assets/javascripts/discourse-assign/routes/group-assigned.js.es6
- assets/javascripts/discourse/templates/components/group-assigned-filter.hbs
- assets/javascripts/discourse/templates/group/assigned.hbs
- assets/stylesheets/assigns.scss
- db/migrate/20210908060141_add_index_to_assigned_to_id_and_type.rb
- plugin.rb
- spec/components/topic_query_spec.rb
- test/javascripts/acceptance/assign-enabled-test.js.es6
- test/javascripts/components/group-assigned-filter-test.js.es6
On the group assignment page, we should be able to display
- all topics assigned to that group + to user belonging to that group
- all topics assigned directly to group
- all topics assigned to individual user
https://user-images.githubusercontent.com/72780/131953304-aae4ad9d-e4fa-4ae8-9af2-47be9ac2eabe.mov
> FEATURE: better UI for group assignments

- plugin.rb
- spec/integration/assign_spec.rb
Send correct messages and correctly unassign/assign to user/group if group PM is archived or moved back to inbox.
> FIX: unassign/assign when group pm is archived

- app/models/assignment.rb
- app/serializers/assigned_topic_serializer.rb
- lib/topic_assigner.rb
- plugin.rb
- spec/serializers/suggested_topic_serializer_spec.rb
With hard refresh, information about assigned user disappeared from suggested topics.
> FIX: add assigned fields to suggested topic serializer

- app/serializers/assigned_topic_serializer.rb
- plugin.rb
We are preloading assigned_to for topic list https://github.com/discourse/discourse-assign/blob/main/plugin.rb#L214
Therefore instead of checking assignment, we should use assigned_to directly on topics for serializers
> FIX: n+1 assignment

- assets/javascripts/discourse/components/remind-assigns-frequency.js.es6
- assets/javascripts/discourse/templates/components/remind-assigns-frequency.hbs
- test/javascripts/acceptance/assign-enabled-test.js.es6
If the user selected Never for their frequency of assigned topic
reminder PMs, the option automatically set back to the default
value (Monthly) because of the user of the `or` computed helper,
which considered the 0 value of Never to be falsey.
This is the same problem that occurred in core which was fixed by
https://github.com/discourse/discourse/commit/d3779d4cf75bd9c21cf61e016047a92fe66d3fdd
We need to be careful around using the `or` helper if any of the
options could be considered falsey.
> FIX: Allow Never selection for frequency of assigned topic reminders

- assets/javascripts/discourse-assign/connectors/advanced-search-options-below/assigned-advanced-search.js.es6
- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
- test/javascripts/acceptance/category-test.js.es6
- test/javascripts/acceptance/search-full-test.js.es6
The first issue is using `updateCurrentUser` when code was conditional
in an initializer. Instead we need to use `needs.user()`.
The second issue was trickier to track down but we were using an
observer in a syncrhnous way which is not allowed in newer Embers. This
removes the observer (and some dead code around it!) so that we can
execute that code synchronously.
> FIX: Tests were broken on Ember CLI

- plugin.rb
On dev environment, when editing a local file, I would often see this error: 
@davidtaylorhq pointed out that this is due to these monkey-patches not being reloadable by Zeitwerk. This doesn't fix the problem for all of the monkey patches, but this Topic one is probably the most common.
> DEV: Fix dev plugin reloading issue

- plugin.rb
When getting a list of private messages assigned to groups/users, we should include :allowed_users to avoid n+1
> FIX: n+1 query on list of private messages assigned

- db/post_migrate/20210714173022_correctly_move_assignments_from_custom_fields_to_a_table.rb
We need two branches of that migration. One when `assigned_to_type` is missing and another when `assigned_to_type` exists.
https://meta.discourse.org/t/db-migration-version-20210714173022-fails-when-having-skipped-post-deployment-migrations-before/204660
> FIX: assignment table migration when SKIP_POST_DEPLOYMENT_MIGRATIONS

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
- assets/stylesheets/assigns.scss
- plugin.rb
- test/javascripts/acceptance/assigned-topic-test.js.es6
A link in the first post will allow going to a specific post assigned to a user or group.
> FEATURE: display indirect assignments in the first post

- plugin.rb
- spec/integration/assign_spec.rb
When an assigned post is moved to the new topic, it becomes topic assignment.
When an assigned post is moved to an existing topic it stays post assignment
> FIX: move post assignment when move post

- config/locales/client.en.yml
- db/post_migrate/20211108023921_change_action_code_href_to_action_code_path.rb
- lib/assigner.rb
We should use relative paths, therefore name change is necessary to avoid confusions. Post migration is added to fix existing data.
Related PR: https://github.com/discourse/discourse/pull/14834
> FIX: rename action_code_href to action_code_path

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
Only show mobile re-assign options if user has permission to assign
Fixes: https://meta.discourse.org/t/discourse-assign/58044/155?u=isaacjanzen
> FIX: Update Re-assign view permissions

- plugin.rb
When an assigned post is deleted, we should not error. For now, assignment object is left untouched to not lose information when post is `undeleted`.
We can change that behaviour later if we decide that assignments should be deleted as well.
> FIX: no error when assigned post is deleted

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
- config/locales/client.en.yml
- lib/discourse_assign/helpers.rb
- plugin.rb
- test/javascripts/acceptance/never-track-assign-reason-test.js.es6
When the user "never" tracks topics, 
We want to show a more accurate tracking message when he gets assigned to a topic
> Show custom topic tracking message when the user 'never' automatically tracks topics and gets assigned

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
- config/locales/client.en.yml
- Update aria labels on mobile and for re-assign dropdown
- Fixes: https://dev.discourse.org/t/quicker-assign-to-self-when-group-is-assigned/54647/33?u=isaacjanzen
> FIX: Update aria-labels on mobile / dropdown

- lib/assigner.rb
- spec/integration/assign_spec.rb
When post is already assigned to user/group then don't allow assigning a topic to that user/group.
Similarly, right now when topic is already assigned we are not allowing to assign a post that that user.
> FIX: dont allow assigning user to topic when post assigned

- app/models/assignment.rb
- app/serializers/assigned_topic_serializer.rb
- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
- assets/javascripts/discourse/components/assign-actions-dropdown.js.es6
- config/locales/server.en.yml
- config/settings.yml
- db/migrate/20211206060512_add_active_to_assignments.rb
- db/post_migrate/20211206081254_move_prev_assigned_custom_fields_to_assignments.rb
- lib/assigner.rb
- lib/discourse_assign/helpers.rb
- plugin.rb
- spec/integration/assign_spec.rb
- spec/lib/assigner_spec.rb
- spec/serializers/post_serializer_spec.rb
- test/javascripts/acceptance/assigned-topic-test.js.es6
When topic is closed, we mark assignments as "inactive". Then, when it is reopened and setting reassign_on_open is enabled, we bring back previous assignments.
We were already using custom fields for archive message and move to inbox. I changed custom fields solution to use active flag on Assignment model.
Also, very similar solution was used when post is deleted (mark assignment as inactive) and recovered (change flag to true if `reassign_on_open`). The difference is that when the post is deleted, small action is deleted as well because the link to the deleted post was causing 404. I added an explicit post custom field called `action_code_post_id` to have strict link between post and small action. That gives safety that deleted small action really is related to deleted post. …
> FEATURE: active flag for assignments

- plugin.rb
Post should be always unassigned when deleted. They are hidden, and it may cause a lot of confusion. For example, when a user wants to assign topic, and it cannot be done because existing assignment to deleted post.
> FIX: always unassign posts when deleted

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js.es6
- config/locales/client.en.yml
When trying to bulk assign topics to a user via bulk topics action modal
the modal was broken because the key "model.description" was missing.
This commit adds key "model.description" and adds a new locale for it to
indicate that this action will be performed on multiple topics.
> FIX: bulk assign modal was broken

- assets/javascripts/discourse/templates/modal/assign-user.hbs
- assets/stylesheets/assigns.scss
When user is on holiday, mark avatar with calendar icon.
In this case, urgent topics can be assigned to an available team member.
> FEATURE: holiday icon for suggestions

- app/controllers/discourse_assign/assign_controller.rb
- plugin.rb
- spec/components/search_spec.rb
- spec/components/topic_query_spec.rb
There is an active flag for assignments. It is used to bring assignments back when topic is reopened.
However, when assignment is inactive, it should not be displayed on assigned list or search.
> FIX: don't display inactive assignments

- app/controllers/discourse_assign/assign_controller.rb
- plugin.rb
- spec/requests/list_controller_spec.rb
After a topic is closed, the assignment is not deleted but becomes
inactive. When this happened, it was not removed from the assignments
count or list.
> FIX: Count and show only active assignments

- config/locales/server.en.yml
- jobs/regular/assign_notification.rb
- spec/jobs/regular/assign_notification_spec.rb
When topic is assigned to group, then notification should be different to distinguish from direct assignments.
> FIX: better group assign message

- lib/assigner.rb
- spec/lib/assigner_spec.rb
If `SiteSetting.unassign_on_close` is enabled, an Assignment record can still exist, but be set to inactive, when a Topic is closed.
Inactivement Assignments should be ignored when comparing to the maximum permitted number of assigned topics.
> FIX: Exclude inactive assignments from assigned_total count

- assets/javascripts/discourse/templates/group-topics-list.hbs
- assets/javascripts/discourse/templates/user-assigned-topics.hbs
Follows core changes, more details in https://github.com/discourse/discourse/pull/15758.
> A11Y: Use `autocomplete=off` for search inputs

- app/controllers/discourse_assign/assign_controller.rb
- plugin.rb
The query for counts and list were different and the count did not
match the number of topics from the list.
Needs https://github.com/discourse/discourse/pull/15742
> FIX: Reuse topic query method to find group topics

- .discourse-compatibility
https://github.com/discourse/discourse-assign/commit/c8fc42b60f42ccc8acc6257f3c3e7444ab5a6e61 uses an API in core that is not present in Version 2.8.1
> DEV: Update .discourse-compatibility for stable branch.

- assets/javascripts/discourse/templates/user-assigned-topics.hbs
The layout can support it, and this extra information seems useful. 
Related discussion: https://meta.discourse.org/t/show-last-poster-in-assignment-list/220298
Before:
After:
> UX: Show posters on assigned topic list

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js
- test/javascripts/acceptance/assigned-topic-test.js
Fixes https://meta.discourse.org/t/public-assigns-shows-reassign-button/224860
> When “public assigns” is enabled in the assign plugin, a regular user sees a drop down button which looks like they are able to reassign the topic. The button does not actually work though.
> FIX: Hide footer action button when user cannot assign

- assets/javascripts/discourse/templates/components/assigned-topic-list.hbs
I previously had enabled these on the user assigned topic list, and there's space to show them on the group assigned list as well. Consistency!
Before:
After:
User assigns (changed to match this):
> UX: show posters on group assign list

- config/locales/client.en.yml
The modal doesn't just reassign any more, so a more generic "Edit Assignment..." is more accurate
> FIX: Rename button

- plugin.rb
- spec/serializers/user_bookmark_base_serializer_spec.rb
Adds support for polymorphic bookmarks in the serializer extensions
and preloaders for bookmarks.
Specs are skipped for now for the serializer but they do
work without the use_polymorphic_bookmark guard in the plugin.rb
> FIX: Polymorphic bookmarks support

- assets/javascripts/discourse-assign/controllers/assign-user.js
- test/javascripts/controllers/assign-user-test.js
Quite literally it.
Previously, clicking on the user suggestion immediately triggered the assign and closes the modal. It was reverted (https://github.com/discourse/discourse-assign/pull/326) because there was an additional note box to fill in. But folks prefer immediately assigning despite notes not filled 🤷‍♀️
> FIX: Assigning a user without notes assigns and closes the modal

- config/locales/client.en.yml
- lib/assigner.rb
- spec/lib/assigner_spec.rb
Shows the assignment note in moderator post.
Note there were no migrations to retroactively add the notes into small action posts
- A small action post generated from assignment has no relation to its topic/post
- its `PostCustomField`s used in assign are used elsewhere as well (e.g. `action_code_who` etc)
- Vice versa, an assignment does not have relationship to its generated small action post
Each note modification also adds a moderator post, rather than modify the previous post. If we wish to have that, it's possible too.
> FEATURE: Shows note in moderator post

- plugin.rb
- spec/serializers/user_bookmark_base_serializer_spec.rb
This removes the use_polymorphic_bookmarks site setting
guard and promotes that code to the only code used.
> FEATURE: Promote polymorphic bookmarks

- config/locales/server.en.yml
- spec/lib/random_assign_utils_spec.rb
It's a minor copyedit to remove group mention from the post raw. Else it sends a notification to all group members when no one is found to be assigned.
> UX: don't mention the group when no one is assigned.

- lib/random_assign_utils.rb
- spec/lib/random_assign_utils_spec.rb
While assigning a random user in group to the topic posts, if we didn't include the users who were assigned to indivitual posts then the same users will be assigned again and again.
> FIX: include users who were assigned to a post instead of topic.

- lib/assigner.rb
- spec/lib/assigner_spec.rb
- spec/lib/topic_query_spec.rb
We are already checking that assignee has access to the private message. However, admin still can be assigned as technically they have access.
We should ensure that assignee has direct access to the message.
> FIX: ensure that assignee is participant of pm

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js
I initially wrote a widget test for 
```
Component | Widget | transformed post-stream
```
but ultimately ditched it as the `componentTest` initialization was not working out well with the plugin initializer. Essentially I had to set some site-settings in the test setup, but it triggered too late in the flow to test the side effect.
> FEATURE: Allows note to be edited

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js
Unfortunately, similar to https://github.com/discourse/discourse-assign/pull/350, this line is not easily testable due to plugin initialization occurring before `beforeEach`.
> FIX: Fix a bug where a note change was ending in a full blown whisper

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js
- test/javascripts/acceptance/assign-sidebar-test.js
Assignments can already be accessed via sidebar.
> UX: Don't display assign user menu glyph when sidebar is enabled

- test/javascripts/acceptance/assigned-topic-test.js
- test/javascripts/fixtures/notifications-fixtures.js
Follow up of https://github.com/discourse/discourse-assign/pull/306#issuecomment-1071953653
@tgxworld Is this what you had in mind?
Can't get it to pass tho, any ideas @CvX ?
> DEV: Add acceptance tests for assignment notifications

- assets/javascripts/discourse-assign/controllers/assign-user.js
- assets/javascripts/discourse/templates/modal/assign-user.hbs
This commit allows submitting the assign modal with
control/meta+enter when the textarea is focused.
The rest of the modal can already be submitted with
this key combo.
> FEATURE: Allow submitting the assign modal with ctrl+enter

- app/controllers/discourse_assign/assign_controller.rb
- app/models/assignment.rb
- assets/javascripts/discourse-assign/controllers/assign-user.js
- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js
- assets/javascripts/discourse/services/task-actions.js
- assets/javascripts/discourse/templates/modal/assign-user.hbs
- config/locales/client.en.yml
- config/locales/server.en.yml
- config/settings.yml
- db/migrate/20220728171436_add_status_to_assignments.rb
- lib/assigner.rb
- lib/discourse_assign/helpers.rb
- lib/validators/assign_statuses_validator.rb
- plugin.rb
- spec/components/search_spec.rb
- spec/lib/assigner_spec.rb
- spec/requests/assign_controller_spec.rb
- spec/serializers/post_serializer_spec.rb
- spec/serializers/topic_view_serializer_spec.rb
- test/javascripts/acceptance/assign-enabled-test.js
- test/javascripts/acceptance/assigned-topic-test.js
- test/javascripts/unit/task-actions-test.js
Adds a new plugin setting that when enabled adds a status field for every assignment. This setting defaults to off.
The possible status for an assignment are customizable via yet another new setting, and the first one on this list will be the default status for new assignments.
The status is not yet show anywhere except the assign modal and the small action posts in topics at the moment. Adding status to the assignment list for users and groups will be handled in the near future.
> FEATURE: Assign Status

- jobs/regular/assign_notification.rb
- lib/assigner.rb
- plugin.rb
- spec/jobs/regular/assign_notification_spec.rb
- spec/jobs/regular/unassign_notification_spec.rb
This change makes it possible to associate an assign notification with the `assignments` record that creates the notification. It'll be needed for the assignments tab in the new experimental user menu, see https://github.com/discourse/discourse/pull/17379.
> DEV: Add assignment ID to assign notification data

- lib/assigner.rb
- spec/lib/assigner_spec.rb
The check existed, but its implementation was incorrect and it did not
work when the target was a post.
> FIX: Check if assignment has same user and details

- app/controllers/discourse_assign/assign_controller.rb
- config/locales/client.en.yml
- lib/random_assign_utils.rb
- plugin.rb
- spec/lib/random_assign_utils_spec.rb
- spec/requests/assign_controller_spec.rb
There were two problems with the way current automation script for automatic assignment works:
* it tried to assign users that were not allowed to be assigned because they were not part of groups that are allowed to use discourse-assign - fixed by skipping users that are not a part of assign_allowed_on_groups groups
* it assigned new users - fixed by adding a new user that can skip new users
> FIX: Find better users for automatic assignment

- plugin.rb
- spec/lib/assigner_spec.rb
This PR fixes the issue that results when attempting to delete a post through bulk deletion when the post's corresponding post action is already deleted
Issue Preview:
https://user-images.githubusercontent.com/30090424/186519819-d39e02e6-f99f-4967-88be-b09144803ac2.mov
This PR resolves this fix by breaking out of the loop for deleting the corresponding post action, if the post action is already deleted.
> FIX: Error bulk deleting posts when action post is already deleted

- lib/assigner.rb
- spec/lib/assigner_spec.rb
Only 5 assignments can exist simultaneously for a topic or its post.
The code that counted the assignments did not ignore the inactive
assignments which made the limit check more strict than it should have
been.
> FIX: Count only active assignments when checking limits

- app/serializers/assigned_group_serializer.rb
- plugin.rb
- spec/requests/search_controller_spec.rb
The basic group serializer complains that the flair_upload relation has to be eager loaded when attempting to included assigned groups in search results, which is a consequence of using strict loading during search's preload to avoid N+1.
Eager loading the association during this would definitely fix the problem, but is it the right solution? It seems to me that this serializer does too much, when we only need a small number of attributes to display the assigned widget. Instead, this commit adds a lightweight custom serializer which grabs only the essentials for it to work.
> FIX: Don't fail because flair_upload wasn't eager loaded

- assets/javascripts/discourse/initializers/assign-user-menu.js
- test/javascripts/acceptance/assigns-tab-user-menu-test.js
As of https://github.com/discourse/discourse/commit/12ebdf0ff0f742d5363527908a4a2721e41b00f2, it's possible to make tabs in the experimental user menu link to a page when they're clicked on when they're active. This PR makes the assign tab links to the `/my/activity/assigned` when it's active.
> DEV: Make the assign tab in the user menu link to the assign page

- config/locales/client.en.yml
As of https://github.com/discourse/discourse/commit/496f910f03dfbc0a8021561fa7795a68894ef0e4, core automatically adds title to user menu tabs if an i18n string exists at the key `user_menu.tabs.${tab_id}`. This PR adds a string in the right place so core picks it up and uses it for the assign tab.
> UX: Add title for the assign tab in the user menu

- assets/javascripts/discourse/templates/modal/assign-user.hbs
This will start working after merging https://github.com/discourse/discourse/pull/18367.
> FEATURE: show user status when assigning topics and posts

- assets/javascripts/discourse/templates/components/group-assigned-menu-item.hbs
- assets/javascripts/discourse/widgets/assigned-notification-item.js
- plugin.rb
- test/javascripts/acceptance/assigned-notification-item-test.js
The same "user-plus" icon was used for both user and group assigned notifications.
> FIX: Show group icon for group notifications

- spec/components/topic_query_spec.rb
See https://github.com/discourse/discourse/pull/18437, we are removing any references to enable_personal_messages in core and using only personal_message_enabled_groups, which requires auto groups to be assigned in certain specs for them to keep working.
> DEV: Fix specs for personal_message_enabled_groups setting

- test/javascripts/acceptance/never-track-assign-reason-test.js
This slight core change breaks this test
https://github.com/discourse/discourse/pull/18691
> DEV: Fix test for core change

- spec/lib/assigner_spec.rb
There is almost no reason for us to use `Fabricate.build` which does not persist the record to the database and is not what we encounter in production.
> DEV: Persist records to DB in tests

- lib/assigner.rb
- spec/lib/assigner_spec.rb
If a topic is initially assigned to user A then reassigned to user B, this change will make it so that notifications sent to user A are removed. This matches the plugin's behaviour when unassigning a topic.
> FEATURE: Cleanup notifications when reassigning

- config/locales/server.en.yml
- spec/jobs/regular/assign_notification_spec.rb
The original message is quite hard to read and multiple translators suggested the rephrase.
> UX: Rephrase notification message

- spec/integration/assign_spec.rb
This spec has been detected to be flaky by
https://github.com/discourse/flaky-tests-detective which we run
internally. However, I could not reproduce the flakiness after multiple
attempts so I rewrote the assertions such that we set up the
expectations of what `Assignment#assigned_to_id` should be before and
after the triggering of the DiscourseEvent.
> DEV: Change flaky spec to provide more information when it fails

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js
[Meta topic](https://meta.discourse.org/t/404-error-page-is-opened-after-clicking-on-assignee-tag-under-the-title/249333).
The tag links added to the topic header extras aren't aware of subfolder usage, e.g. the topic URL would be generated as a vanilla `/t/:id` URL. The same applies to post assignments.
This change fixes that by passing the link URL through the [`getURL`](https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse-common/addon/lib/get-url.js#L6) helper.
I searched around for tests that simulate subfolders, but couldn't find any. If anyone know these exist and can point me to them, that'd be great.
> FIX: Build correct assign tag links when using subfolders

- .github/workflows/plugin-tests.yml
- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js
- lib/assigner.rb
- spec/system/assign_topic_spec.rb
- spec/system/page_objects/modals/assign.rb
- spec/system/page_objects/pages/topic.rb
1. Assign a topic to someone
2. Close the topic with the setting unassign_on_close enabled
3. Assign the topic to the same user as before
This caused small broken or empty posts to be displayed.
> FIX: Broken posts when assigning a closed topic

- spec/system/page_objects/modals/assign.rb
Since now the assignee chooser opens automatically, clicking on it was causing it to close
> FIX: System tests failing due to assignee chooser

- db/migrate/20230113025043_deactivate_assignments_to_deleted_targets.rb
Before the implementation of the `post_destroyed` event handler in the plugin, soft deleting assigned posts/topics did not deactivate the assignment.
This left sites which assigned and deleted posts/topics before the introduction of the event handler with 'orphaned' assignments in the UI.
This change deactivates these orphaned assignments.
> FIX: Deactivate active assignments attached to deleted targets

- app/models/assignment.rb
- db/migrate/20230112033741_add_topic_id_index_to_assignments.rb
- lib/assigner.rb
- spec/lib/assigner_spec.rb
Previously, when topic was already assigned 5 times, reassign was not possible. User had to first unassign topic and then assign to someone else.
> FIX: reassign when assignment limit is fulfilled

- assets/stylesheets/assigns.scss
This cut-off
to be able to extend beyond the modal box
> UX: fix list being limited by modal size

- assets/javascripts/discourse/templates/modal/assign-user.hbs
This does not work as expected and can lead to a worse user experience.
> FIX: Do not expand if assignee username present

- plugin.rb
- spec/requests/search_controller_spec.rb
When assignment data is preloaded for search results, cache variable should be set when topic is assigned but also when topic is not assigned to avoid additional queries.
> FIX: n+1 in search result

- test/javascripts/acceptance/user-private-messages-assigned-test.js
Core is moving towards the redesigned user page navigation menu so the
old test is no longer required.
> DEV: Remove viewing personal messages test on old user navigation menu

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js
We already handle the space between icons and text with margins. 
Before:
After:
> UX: remove whitespace in assign tag

- assets/javascripts/discourse/components/assigned-topic-list.js
Re-exporting the TopicList component as-is leads to unexpected behavior when colocating templates because `AssignedTopicList` === `TopicList`. Extending it gives the component its own identity.
> DEV: Make assigned-topic-list a real component

- assets/javascripts/discourse/components/basic-assigned-topic-list.js
Re-exporting the BasicTopicList component as-is leads to unexpected behavior when colocating templates because `BasicAssignedTopicList` === `BasicTopicList`. Extending it gives the component its own identity.
Similar to 8ba7b0727a3ad8673b0ff467c2925ab7ef8b4524
> DEV: Make basic-assigned-topic-list a real component

- assets/stylesheets/assigns.scss
Fixes an issue caused by this commit: https://github.com/discourse/discourse/pull/20643
Before (note the status alignment):
After:
> UX: fix status alignment after core change

- lib/discourse_assign/list_controller_extension.rb
- plugin.rb
- spec/requests/list_controller_spec.rb
A small regression of https://github.com/discourse/discourse-assign/pull/446, causing `http://<route>/u/<user>/messages/assigned` to end up 404-ing.
A lil proof it's fine meow :sparkles:
> FIX: Also evaluate list controller extensions

- assets/javascripts/discourse-assign/initializers/extend-for-assigns.js
_Reported here_: https://meta.discourse.org/t/reassigning-to-a-group-creates-a-u-link-in-the-group-mention/263659
Reassigning to a group creates an `/u/` link in the `@group` mention instead of `/g/`.
The reason is the `reassigned_group` group small post action code is not registered, thus creating a user link by default.
Related Discourse code:
https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/app/widgets/post-small-action.js#L12-L27
https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/app/widgets/post-small-action.js#L82-L84
> FIX: Reassigning to a group creates an incorrect mention's link

- plugin.rb
- spec/integration/assign_spec.rb
We have replaced the `#pluck_first` freedom patch with the native `#pick` in core [here](https://github.com/discourse/discourse/pull/19893).
This change is updates this plugin in the same fashion.
> DEV: Replace #pluck_first monkey patch with native #pick

- test/javascripts/acceptance/assigns-tab-user-menu-test.js
This PR removes the usage of `redesigned_user_menu_enabled: true` in the `assigns-tab-user-menu-test.js` as its no longer needed as of the removal of the legacy user menu in core (https://github.com/discourse/discourse/commit/082821c754ce95aefdc5c69e6d0eea4057bcd5b5)
A `.discourse-compatibility` file entry is not needed in this case as there is already a commit hash present for `3.1.0.beta3`
> DEV: Remove `redesigned_user_menu_enabled: true` in tests

- config/locales/server.en.yml
- config/settings.yml
- lib/assigner.rb
- spec/lib/assigner_spec.rb
When a group or user is assigned to a personal message, if they are not already a participant then invite them to the PM before assignment.
> FEATURE: invite user/group to PM if not a participant already.

- lib/assigner.rb
- spec/lib/assigner_spec.rb
Otherwise, when an allowed group member is assigned to the PM it invites the user (which is unnecessary) and creates a public small post for the invite.
> FIX: don't invite user when already a member of an allowed group.

- lib/assigner.rb
- spec/lib/assigner_spec.rb
We don't want to invite a group when all of its members are part of another group that is already allowed to the topic.
> FEATURE: skip group invite if all members can see topic already.

- app/controllers/discourse_assign/assign_controller.rb
- app/models/assignment.rb
- spec/fabricators/assignment_fabricator.rb
- spec/models/assignment_spec.rb
- spec/requests/assign_controller_spec.rb
Related: https://meta.discourse.org/t/bad-group-assignment-count/252636
Use the `Assignment` count rather than the number of `Topic` assigned. 
e.g. John can be assigned to topic_id: 1, and Jane can be assigned to a post within topic_id: 1. This will result in 1 rather than 2.
Before:
The sum doesn't add up.
There's a flicker in the number in the nav.
https://github.com/discourse/discourse-assign/assets/1555215/786d18ee-1505-41ff-b543-2cd81ce2ff09
After:
The nav number will just be a sum of all assignments, user+group.
https://github.com/discourse/discourse-assign/assets/1555215/12f28b66-238b-4445-8229-127e73825e52
There is still another bug we are seeing where it's likely that this line with the `limit` is causing issues with accuracy. But that will be looked at in another PR. …
> FIX: Sum assignments for group and group users

- spec/requests/assign_controller_spec.rb
This was causing the tests to be flaky with the following errors on CI:
```
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_assignments_on_target_id_and_target_type"
DETAIL:  Key (target_id, target_type)=(39, Topic) already exists.
```
> DEV: Fix incorrect fabrication leading to index violation errors

- spec/system/assign_topic_spec.rb
We have been seeing tests failures due to errors like
```
Capybara::ElementNotFound:
Unable to find css "#topic-footer-button-assign"
```
when running our system tests in CI. However, I can't quite figure out
why that is happening and have invested way too much time to do so.
Therefore, I'm trying to fix this by closing a topic via the topic
timeline controls instead of the footer button instead.
Example of test failure: https://github.com/discourse/discourse/actions/runs/5525940028/jobs/10080088908
> DEV: Try to make system tests more stable

- spec/system/assign_topic_spec.rb
We already tried to make this spec more reliable in https://github.com/discourse/discourse-assign/commit/eb3b97b834a84a588da36a45a29279e6dd83d406 but that didn't work out.
https://github.com/discourse/discourse/actions/runs/5694495045/job/15435791690?pr=22860
> DEV: skip flakey spec

- app/jobs/scheduled/enqueue_reminders.rb
- spec/jobs/scheduled/enqueue_reminders_spec.rb
t/105676
When a user sets their reminder frequency to be "daily", there's a chance that they actually only get it sent every two days.
(/my/preferences/notifications)
This is likely happening as our `EnqueueReminders` sidekiq job runs every `1.day`, issuing a second job `RemindUser` which updates the `last_reminded_at` value to be a bit after the time when the sidekiq job gets done. The list of users to send reminders to depends on `last_reminded_at` being more than the user set reminder frequency, resulting in the bug that the reminder only triggers on the next day.
> FIX: Fix reminder frequency not getting sent daily when early by a few seconds/minutes

- app/jobs/scheduled/enqueue_reminders.rb
- spec/jobs/scheduled/enqueue_reminders_spec.rb
Continuing from https://github.com/discourse/discourse-assign/pull/496
The buffer value introduced here was not enough. We are seeing that the deviation across emails across the two days (when it should be one day) is two hours. 
Day 1 email at 5:47PM. Assuming the next sidekiq job triggers at 5:46PM (at an earlier time the next day), the reminder will not be sent
Day 3 email at 4:19PM, about 2 hours earlier in the day. 
So we will use 2 hours as a buffer.
> DEV: Increase the buffer used to determine whether to send out the reminder email

- config/locales/client.en.yml
Move comment for `assign_post_to_multiple` out of the translation value
> FIX: move comment out of the translation value

- app/jobs/scheduled/enqueue_reminders.rb
Without ||=, ruby warns the const is being reassigned all the time.
> DEV: Fix REMINDER_BUFFER_MINUTES const reassignment warning

- assets/javascripts/discourse/components/assigned-topic-list-column.gjs
The `_Test` suffix shouldn't have been included in 89807545a4869fb917ce6c754c063c5fcb1afb2e. No functional change.
> DEV: Update AssignedTopicListColumn class name

- assets/javascripts/discourse/routes/group-assigned.js
Uses the router service for redirecting instead of `this.transitionTo`. Also removes the first branch of logic, which was unnecessarily redirecting to the current route (and led to an infinite loop with the modern API)
> DEV: Resolve routing method deprecation

- lib/assigner.rb
- spec/lib/assigner_spec.rb
Currently, when unassigning a topic, we change the topic's notification level to `TopicUser.notification_levels[:tracking]` if it was originally set by a plugin and the user was not watching it originally.
We've found that assignees tend to want to still watch the topic for any input despite being unassigned.
This PR removes that notification level change, and keeps notification level as-is.
> UX: Don't change topic notification level when unassigning

- assets/javascripts/discourse/components/assigned-topic-list-column.gjs
- assets/javascripts/discourse/raw-views/assign-topic-buttons.gjs
This cleans up the markup a bit, so instead of a `div` as a table child we use the `td` and removes the internal wrapper. This fixes an issue with a double highlight while using j/k navigation highlighting caused by the nested `td`. 
Before:
```html
<div>
<td>
dropdown here
</td
</div>  
```
After:
```html
<td>
dropdown here
</td
```
> UX: simplify markup to fix j/k highlighting

- spec/lib/assigner_spec.rb
A fix for this error:
```
1) Assigner invite_on_assign doesn't invite group if all members have access to the PM already
Failure/Error: expect(topic.allowed_groups).to eq([group1, group2])
expected: [#<Group id: 88, name: "my_group_47", created_at: "2023-11-02 06:04:13.051487280 +0000", updated_at: "2023-11-02 06:04:13.051487280 +0000", automatic: false, user_count: 0, automatic_membership_email_domains: nil, primary_group: false, title: nil, grant_trust_level: nil, incoming_email: nil, has_messages: false, flair_bg_color: nil, flair_color: nil, bio_raw: nil, bio_cooked: nil, allow_membership_requests: false, full_name: nil, default_notification_level: 3, visibility_level: 0, public_exit: false, public_admission: false, membership_request_template: nil, messageable_level: 1, …
```
> DEV: Use match_array for spec allowed groups

- assets/javascripts/discourse/components/user-menu/assigns-list.js
- spec/fabricators/notification_fabricator.rb
- spec/system/page_objects/pages/user_menu.rb
- spec/system/user_menu_spec.rb
The recent changes to the user menu changed how we were ordering the items in it. A small bug was noticed though, as we’re not displaying the unread assignments at the very top.
This PR fixes the ordering like this:
- Unread individual assignment notifications
- Unread group assignment notifications
- Read individual assignments
- Read group assignments
In each group of items, they are sorted by date, the most recent ones being at the top.
> FIX: Order items properly in user menu

- config/locales/client.en.yml
- config/settings.yml
This is so the plugins settings are better categorized in the site settings UI.
> DEV: Change settings root from plugins: to discourse_assign

- spec/system/page_objects/modals/assign.rb
- test/javascripts/acceptance/assigns-tab-user-menu-test.js
https://github.com/discourse/discourse/pull/23967
> DEV: Update tests for core change

- lib/random_assign_utils.rb
- spec/lib/random_assign_utils_spec.rb
Currently, when the auto-assign logic can’t find a user to assign, it will fail saying there was no one to assign. The current logic is this one:
- Don’t pick anyone who’s been picked in the last 180 days
- If no one has been found, then try the same thing but only for the last 14 days. While this is working relatively well for large enough groups, it doesn’t work at all with very small groups (like 2 people) and it creates unnecessary noise.
This patch addresses this issue by adding a fallback to the current logic. Now, if the two first rules fail, instead of saying that no one was assigned, we assign the least recently assigned person. This way, the logic will continue to work with large groups but will also work nicely with small groups.
> FEATURE: Add a fallback to auto-assign

- spec/lib/random_assign_utils_spec.rb
Sometimes, the topic id actually exists for that spec (id being 1) and it will raise about not finding the group id instead of not finding the provided topic because the assignees group wasn’t provided in the `fields` parameter.
> DEV: Fix a flaky spec

- spec/system/assign_topic_spec.rb
The spec is flaky and it seems to be DB transaction related where after signing in as a user, the failure screenshot shows that the user has not been signed in.
What does this change do?
Set `capture_log: true` which will log all ActiveRecord DB statements execute while running the spec.
> DEV: Fix flaky system tests

- spec/system/assign_topic_spec.rb
The tests are supposedly flaky but we are unskipping them and capturing
logs to figure out why.
> DEV: Unskip flaky tests and capture logs

- spec/system/assign_topic_spec.rb
We have been getting flaky test failures from these specs and the failure screenshot shows that the user is not logged in when it is supposed to be. Futher investigation shows that when the test flakes, it is because the request to view the topic is using an auth token that is different from the one which was created when the user was signed in.
What does this change do?
1. Add the `capture_log` metadata to all the tests in this file.
2. Enables the `verbose_auth_token_logging` site setting to give us more debugging information in the logs.
> DEV: Capture logs for all tests in `spec/system/assign_topic_spec.rb`

- spec/system/assign_topic_spec.rb
We believe we have figured out the problem and not longer need the debugging information.
> DEV:  Remove `capture_logs: true` metadata

- assets/javascripts/discourse/components/assign-user-form.hbs
With the new mobile modal we can now do this with no issue. Prior to this change we would have to click two times on search input to show keyboard, now only one.
> UX: autofocus assignee input

- lib/assigner.rb
- spec/lib/assigner_spec.rb
At the moment, it's possible to have maximum [5 assignments](https://github.com/discourse/discourse-assign/blob/08c2a4e0f392718fd821ce10a52186f04323e439/lib/assigner.rb#L7) per topic (that includes topic and post assignments). When trying to assign more, this message appears:
One possible edge case here is reassigning a topic or a post. Reassignment doesn't lead to exceeding the limit, and therefore it should be possible. But at the moment we handle correctly only _topic_  reassignments, while when reassigning a _post_, we show the error message "the limit has been reached".
This PR makes post reassignments work correctly too.
> FIX: Assignments limit shouldn't prevent from reassigning a post

- assets/javascripts/discourse/components/assign-actions-dropdown.js
We've noticed problems when unassigning a topic on the `activity/assigned` page using this button:
One of two incorrect things happens when pressing this button:
1. The first topic on the page gets unassigned instead of the selected one
2. No topics get unassigned (that happens when the first topic on the list is not assigned and only has assigned _posts_)
That happens because this handler for all buttons somehow always use the same state - the state of the first topic on the page:
https://github.com/discourse/discourse-assign/blob/f2906e088561a970e14049273a5be9669eef2672/assets/javascripts/discourse/components/assign-actions-dropdown.js#L55-L68
There seem to be some nuances in select-kit and I'm not sure whether this should be qualified as a bug in select-kit. However, I've noticed that …
> FIX: Unassign buttons on the activity/assigned page don't work

- assets/javascripts/discourse/connectors/groups-interaction-custom-options/assignable-interaction-fields.hbs
- assets/javascripts/discourse/connectors/groups-interaction-custom-options/assignable-interaction-fields.js
- spec/system/group_preferences_spec.rb
Prior to this fix the state change was not reflected in the UI when changing the "who can assign" preference of a group.
This was actually saved in the backend but would require a full page refresh to see the updated state on the group preferences page.
> FIX: correctly refresh UI when changing group preference

- assets/javascripts/discourse/components/topic-level-assign-menu.js
We've noticed that sometimes it looks like this:
Turned out that happens when a topic has several assignments and those contain assignments to users _and_ to groups. We don't show avatars for groups, but the code saw there are several assignees and applied overlapping styling.
I corrected the logic, and that fixed the issue.
Here is how avatars on this button behave. If there are from one to many assignments on the topic, but all the assignees are groups, we don't show avatars, only label:
If there are from one to many assignments to the same user we show the avatar of that user (and even if there are also assignments to groups there is no overlapping):
And if there are from two to many assignments to different users, we show avatars of first two users:
> FIX: Unassign label sometimes touches avatar

- app/serializers/assigned_group_serializer.rb
- assets/javascripts/discourse/initializers/extend-for-assigns.js
- lib/discourse_assign/helpers.rb
- plugin.rb
- spec/components/search_spec.rb
- spec/requests/search_controller_spec.rb
- spec/serializers/flagged_topic_serializer_spec.rb
- spec/serializers/post_serializer_spec.rb
- spec/serializers/user_bookmark_base_serializer_spec.rb
- test/javascripts/acceptance/assigned-topic-test.js
Both fields are unnecessary and should not be included in the serializer to reduce payload.
> DEV: remove assign_path and assign_icon from seralizers

- config/locales/server.en.yml
- config/settings.yml
- lib/pending_assigns_reminder.rb
- spec/jobs/scheduled/enqueue_reminders_spec.rb
User can define a threshold for the pending assign reminder.
> FEATURE: Add pending assign reminder threshold setting

- app/jobs/scheduled/enqueue_reminders.rb
- spec/jobs/scheduled/enqueue_reminders_spec.rb
This is a follow-up from this commit - https://github.com/discourse/discourse-assign/commit/e3c24ba2f2c24fe073d7e65e5f247849311894f6
The commit added a threshold setting for admin to configure how many assignments a user needs to get the assignment notification. This query here did not allow for the new setting to be `1`.
> FIX: Respect pending_assign_reminder_threshold in enqueue_reminders

- assets/stylesheets/assigns.scss
The core font-size bump up to 16px made this avatar a little taller, which made the button slightly taller than the others (which also caused the others to increase their height, due to `align-items: stretch;` on the parent container). 
Before:
After:
> UX: smaller avatar size in button to prevent height change

- assets/javascripts/discourse/controllers/group-assigned-show.js
- assets/javascripts/discourse/templates/group-assigned-show.hbs
- spec/system/group_assigned_spec.rb
Since a previous refactor the bulkSelectHelper was not correctly passed in the custom topic list page of this plugin.
A spec has also been added.
> FIX: ensures topics can be bulk managed on group page

- assets/javascripts/discourse/initializers/extend-for-assigns.js
- spec/system/bulk_assign_spec.rb
- spec/system/group_assigned_spec.rb
- test/javascripts/acceptance/bulk-actions-test.js
The PR https://github.com/discourse/discourse/pull/28003 in core
removes the experimental status of new topic bulk actions, we
can now use it for everything from now on. After this and the
core PR is merged we can reintroduce the specs.
> DEV: Use new topic bulk action functionality for everything

- lib/discourse_assign/group_extension.rb
I noticed this error in production log but couldn't reproduce it locally. I suspect it's related to a specific combination of plugins.
Ensuring all column names are not ambiguous in this query shouldn't hurt and should fix the problem.
context: https://meta.discourse.org/t/unable-to-search-for-users-when-assigning/322934
> FIX: prevents column reference "id" is ambiguous

- plugin.rb
- spec/plugin_spec.rb
This fix addresses an issue if a group is deleted topics will remain
assigned to all group members with no way to un-assign those users from
the original group assignment.
Now if a group is deleted any group assignments are also deleted.
> FIX: If a group is deleted also remove assignments

- spec/system/bulk_assign_spec.rb
- spec/system/page_objects/components/topic_list.rb
Sometimes the target topic can be out of the viewport and this was causing failing specs.
> DEV: ensure bulk action is done before checking for result

- spec/lib/random_assign_utils_spec.rb
Instead of replacing the Rails logger in specs, we can instead use `#broadcast_to` which has been introduced in Rails 7.
> DEV: Don’t replace Rails logger in specs

- app/controllers/discourse_assign/assign_controller.rb
- lib/assigner.rb
- spec/lib/assigner_spec.rb
- spec/requests/assign_controller_spec.rb
This option let's you control whether the added user within a group assignment should be notified or not.
requires https://github.com/discourse/discourse/pull/29741 to ci go green
> FEATURE: Add `should_notify` option to `Assigner#assign`

- plugin.rb
This properly preload assignment statuses on topic lists when they're enabled to prevent N+1.
Internal ref - t/142804
> PERF: N+1 when assignments status are enabled

- assets/javascripts/discourse/components/assignment.gjs
- assets/javascripts/discourse/components/topic-level-assign-menu.js
This PR updates deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
> DEV: Update deprecated Font Awesome icon names

- lib/pending_assigns_reminder.rb
- spec/lib/pending_assigns_reminder_spec.rb
Before this commit, the reminder leaked the total assigned topics count in the title, which is inconsistent with the UI.
In the post raw, it was ensured that it was not being leaked, but the title was still leaking the count.
Also, add specs and update existing ones to ensure the count is not leaked in the title.
How it was looking before(`post.raw`) from specs:
```
You currently have [3 pending assignments](http://test.localhost/u/bruce0/activity/assigned).
- [This is a test topic 1](/t/this-is-a-test-topic-1/169) - assigned less than 1 minute ago
- [This is a test topic 0](/t/this-is-a-test-topic-0/168) - assigned less than 1 minute ago
```
_it should be `2 pending assignments`_
Now:
```
You currently have [2 pending assignments](http://test.localhost/u/bruce0/activity/assigned).
- …
```
> FIX: pending_assigns_reminder reminder leaking total assigned topics count

- assets/javascripts/discourse/components/assigned-to-post.gjs
This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
> DEV: Update more deprecated Font Awesome icon names

- assets/stylesheets/assigns.scss
- test/javascripts/acceptance/assign-disabled-test.js
- test/javascripts/acceptance/assign-enabled-test.js
- test/javascripts/acceptance/assign-enabled-widget-post-menu-test.js
- test/javascripts/acceptance/assigned-topic-test.js
Dependent on https://github.com/discourse/discourse/pull/30132 getting merged.
The UI for the "hidden" topic footer buttons on mobile changes from SelectKit to DMenu, so the specs needed to be updated as such.
> DEV: fix specs with new mobile footer UI

- test/javascripts/acceptance/assign-disabled-test.js
in preparation of https://github.com/discourse/discourse/pull/30242 which might make the assign button appear immediately (when it's the only available option) or behind the "..." dropdown.
> DEV: make specs regarding assign button more lenient

- assets/javascripts/discourse/components/assign-actions-dropdown.js
- assets/javascripts/discourse/components/assign-button.gjs
- assets/javascripts/discourse/initializers/extend-for-assigns.js
- plugin.rb
This PR updates the deprecated `user-times` icon name. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
> DEV: update deprecated icon name from user-times to user-xmark

- assets/javascripts/discourse/components/assignment.gjs
This PR updates the deprecated `search` icon name. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
> DEV: update deprecated icon name search to magnifying-glass

- assets/javascripts/discourse/templates/group/assigned.hbs
- assets/stylesheets/assigns.scss
- assets/stylesheets/mobile/assigns.scss
This fixes the layout after the core change in https://github.com/discourse/discourse/commit/50136ee4e6a07d1b208997b9b9dad3dac49c4468, this nav will need some additional thinking to suit the new layout 
Before:
After:
> UX: fix group assigns layout after core change

- lib/discourse_assign/create_notification.rb
- spec/lib/discourse_assign/create_notification_spec.rb
Fixes a bug where the topic may already be deleted before the notification job runs, causing the job to fail.
> FIX: skip notifications when topic is not found

- lib/assigner.rb
- spec/integration/assign_spec.rb
This change makes it possible to assign the same user to both posts and the original topic.
/t/124663
> FIX: allow user to be assigned to post and topic

- assets/javascripts/discourse/initializers/extend-for-assigns.js
This works alongside https://github.com/discourse/discourse/commit/55a3a4e69ed75b055fb4907ac5370cf1519276c6 to add a customizable tag separator between multiple assigns. This replaces the previous commas implemented in CSS 
Before:
After:
> UX: update for new core tag separator

- spec/system/bulk_assign_spec.rb
- spec/system/group_assigned_spec.rb
Calling `expand_if_needed` is not necessary here.
> DEV: Remove code that is not necessary

- assets/javascripts/discourse/components/assigned-to-post.gjs
- assets/javascripts/discourse/components/topic-level-assign-menu.js
- assets/javascripts/discourse/initializers/extend-for-assigns.js
- lib/assigner.rb
- spec/system/assign_post_spec.rb
- spec/system/assign_topic_spec.rb
The `prioritize_username_in_ux ` site setting is more appropriate since `prioritize_full_name_in_ux ` is used for notifications and is a hidden setting.
> FIX: Incorrect ussage of prioritize_full_name_in_ux replaced by prioritize_username_in_ux

- spec/system/assign_post_spec.rb
Tests are constantly failing when run against the `main` branch of
`discourse/discourse`.
> DEV: Skip broken tests for now.

- assets/stylesheets/assigns.scss
In https://github.com/discourse/discourse/commit/08d99dc44a33b4c9f53ad531693f3db694073a03, tag text color assignments were simplified 
Assign tag colors were a little inconsistent due to core styling conflicts, but now that they're cleaned up the assign tag colors should match throughout the app without this additional style
Examples:
> UX: following 08d99dc, we can remove the separate color assignment

- plugin.rb
- spec/requests/list_controller_spec.rb
The "assigned:\<name\>" filter was already available in the advanced search but it wasn't in the /filter page.
This commit adds that filter allowing anyone to filter topics assigned to either a specific user (using their username) or to a specific group (using its name).
> FEATURE: add "assigned:<name>" filter (in the /filter page)

- assets/javascripts/discourse/initializers/assignment-list-actions.gjs
This PR will add the `assigned-list-item` class to the topic-list-item when on a route that is included in `ASSIGN_LIST_ROUTES`.
> UX: Add class to assign topic list items

- spec/system/page_objects/pages/topic.rb
https://github.com/discourse/discourse/pull/32145 in core
changes the mentions a bit and introduces inline-flex,
which means that part of the content is not visible according
to capybara. Checking for `:all` fixes this.
> DEV: Tweak has_content? check

- assets/javascripts/discourse/components/assigned-to-post.gjs
- assets/javascripts/discourse/components/topic-level-assign-menu.js
- assets/javascripts/discourse/initializers/extend-for-assigns.js
- lib/assigner.rb
- spec/system/assign_post_spec.rb
- spec/system/assign_topic_spec.rb
**Problem**
Part of this code is not wanted in production yet. To avoid causing issues we want to revert to using the `prioritize_full_name_in_ux` site setting
> DEV: Temporarily revert prioritize_username_in_ux for prioritize_full_name_in_ux

- assets/javascripts/discourse/components/assigned-to-first-post.gjs
- assets/javascripts/discourse/components/assigned-to-post.gjs
- assets/javascripts/discourse/components/post-assignments-display.gjs
- assets/javascripts/discourse/initializers/extend-for-assigns.js
- assets/javascripts/discourse/lib/url.js
- spec/system/assign_topic_spec.rb
- test/javascripts/acceptance/assign-disabled-test.js
- test/javascripts/acceptance/assign-enabled-test.js
- test/javascripts/acceptance/assigned-topic-test.js
Requires https://github.com/discourse/discourse/pull/32063
> DEV: Add compatibility with the Glimmer Post Stream
